### ISSUE TITLE
removing "special board in config" 

### ISSUE THREAD

**Issue by ProbablyBlu** [joserodpt/RealScoreboard#49]
when removing the _Special Board_ in the config on version 13 and reload the plugin it still shows the _Special Board_ even when its deleted from the config file

**Comment by neziw** [comment]
I will look into. Thanks.

**Comment by Folas1337** [comment]
Updating from 12-08-2022 Build 1 to 10-11-2022 Build 5 broke my setup now.
It doesn't seem to care about the yaml node "Config.Scoreboard.world.default" but rather the "Config.Scoreboard.world.special" cause even when I remove the special one, it still seems to be taking the special one rather than my configured default.

**Comment by neziw** [comment]
> Updating from 12-08-2022 Build 1 to 10-11-2022 Build 5 broke my setup now. It doesn't seem to care about the yaml node "Config.Scoreboard.world.default" but rather the "Config.Scoreboard.world.special" cause even when I remove the special one, it still seems to be taking the special one rather than my configured default.

https://github.com/JoseGamerPT/RealScoreboard/actions/runs/3498375734 should fix your issue
