### ISSUE TITLE
[BUG] The scoreboard disappears when vanish is used on

### ISSUE THREAD

**Issue by Francesco99d** [joserodpt/RealScoreboard#63]
I am using the plugin on my **Purpur server in 1.19.4** and I noticed that when running the vanish command, the scoreboard disappears. (_I have tried various types of vanish plugins and with all of them there is this problem_)

Video demonstration of the BUG: https://youtu.be/uFxR6gQaGC8

**Comment by joserodpt** [comment]
Hi there! It's not a problem, it's a feature of RealScoreboard. Because vanish plugins normally have their own Scoreboard, RealScoreboard hides itself when it detects that a player is vanished. 

We could make an option in config to prevent that behaviour from happening. Thanks for the report, this will be looked into!

**Comment by Francesco99d** [comment]
Ah okay, I didn't know about this feature.... The strange thing, though, is that the behavior of the scoreboard is reversed; since when I do the /vanish command for the first time, the scoreboard is like it updates, but then it stays there. But when I do the /vanish command again to "become visible again," the scoreboard should come back and instead that is when it is hidden. (It is evident from the video what I am saying). Anyway I will stay waiting for a future version with the possibility to avoid this phenomenon, thanks for the quick reply

**Comment by joserodpt** [comment]
This issue has been fixed with commit https://github.com/joserodpt/RealScoreboard/commit/b2f20315e68acc49b59016c8604fd94377abf4c2, thanks!
